var CONSTANTS = {};
CONSTANTS.METHOD = {};
CONSTANTS.METHOD.GET = 'get';
CONSTANTS.METHOD.POST = 'post';

CONSTANTS.TOKEN_KEY = 'onpanel.token';
CONSTANTS.CART_KEY = 'onpanel.cart';

CONSTANTS.JWT = {};
CONSTANTS.JWT.HEADER = {'alg': 'HS256', 'typ': 'JWT'};
CONSTANTS.JWT.KEY = '616161';
CONSTANTS.JWT.PASS = 'onsol_2015';